version: '1.0'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pokemon
    ports:
      - "5432:5432"
    volumes: 
      - ./schemas:/docker-entrypoint-initdb.d/    
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"   
